:numbered:

= Managing Ansible Automation Platform Execution Environment through GitOps


== Introduction:
Reproducibility and consistency are two key traits that are the driving forces behind the popularity of containers. Consistency is also a principle found within Red Hat Ansible Automation Platform. With only a few lines of YAML-formatted manifests, thousands of instances can be set up and configured unåiformly. While the management of target instances is simple, it is the control node, or where the Ansible execution is initiated, that can  be the most challenging aspect. As Ansible is written in Python, does the machine have the correct version of Python installed?  Are the necessary Python modules installed? Are there any operating system dependencies needed? The list goes on and on.

These concerns, along with many others, led to a desire to leverage the benefits of containers to perform the control node’s role and eventually ushered in the concept of automation execution environments in Ansible Automation Platform 2.

Since we leverage container’s and have a single source of truth, we can use the Git Ops operational framework that takes DevOps best practices used for application development such as version control, collaboration, compliance, and CI/CD tooling, and applies them to infrastructure automation. In this lab we GitOpsify how you create your Execution Environment based on your inputs by just updating Git repo and the rest is take care of giving you Infrastructure as a Code experience. 

== Objective:

This workshop will help users understand how EEs are customized, created and pushed to registry using openshift-pipelines. 

.Covered topics:

. Demonstrate the steps involved in the customizing EEs using Git repository. 

. Demonstrate the steps involved in the creation EEs using openshift-pipelines.

. Demonstrate the steps involved in scanning EEs container images and pushing in central image registry(Automation Hub).

. Demonstrate the steps involved in using custom EEs pushed in registry to run Job template from Automation Controller


== Let's start by understanding EEs:

Automation execution environments are container images on which all automation in Red Hat® Ansible® Automation Platform is run.

They provide a defined, consistent, and portable environment for executing automation, and allow for easier administration of Ansible Automation Platform by the platform administrator.

The best way to build EEs is relying on a new tool provided by Red Hat® Ansible® Automation Platform, the ansible-builder cli. In order to automate the build of EEs, we can make use of OpenShift Pipelines as well.


== Understanding Gitops:

With the demands made on today’s infrastructure, it has become increasingly crucial to implement infrastructure automation. Modern infrastructure needs to be elastic so that it can effectively manage cloud resources that are needed for continuous deployments.
Modern applications are developed with speed and scale in mind. Organizations with a mature DevOps culture can deploy code to production hundreds of times per day. DevOps teams can accomplish this through development best practices such as version control, code review, and CI/CD pipelines that automate testing and deployments.
GitOps is used to automate the process of provisioning infrastructure, in this case custom Execution Environment. Similar to how teams use application source code, operations teams that adopt GitOps use configuration files stored as code (infrastructure as code). GitOps configuration files generate the same infrastructure environment every time it’s deployed, just as application source code generates the same application binaries every time it’s built.
There are four key components to a GitOps workflow, a Git repository, a continuous integration / continuous delivery (CD) pipeline, an application deployment tool, and a monitoring system.
The Git repository is the source of truth for the application configuration and code.
The CI pipeline is responsible for building, testing, and deploying the application.
The deployment tool is used to manage the application resources in the target environment.
